### ISSUE TITLE
how to build on ubuntu18.04?

### ISSUE THREAD

**Issue by lucasjinreal** [clynamen/nuscenes2bag#1]
Hi, I try to built on ubuntu18.04 with melodic

but I can got some errors:
```
  Could not find a package configuration file provided by "rosbag" with any

```

I try to install `sudo apt install ros-melodic-rosbag`, it says this package can not found on ros server

**Comment by clynamen** [comment]
Hello, sorry for the late answer.
I have set up a VM and tried the build in ubuntu 18.04. 
It should be possible to install ros-melodic-rosbag, maybe you had bad luck?
Ubuntu also needs:

- gcc-9 (can be installed via ppa https://askubuntu.com/questions/1140183/install-gcc-9-on-ubuntu-18-04)
- boost >= 1.69.0 (which I suggest to install manually)

**Comment by clynamen** [comment]
Thanks to @ChernoA  work, the code now runs on ubuntu 18.04

I have added a github action for CI integration
