### ISSUE TITLE
Camera Data Synchronization

### ISSUE THREAD

**Issue by StepTurtle** [clynamen/nuscenes2bag#15]
Hi,

I jsut used your tool to convert nuScenes dataset to rosbag and following image shows the topic timestamps.

![nuScenes](https://github.com/user-attachments/assets/1402da57-72a6-4dfe-be7c-665acd39927d)

The blue lines represents the timestamp the message arrived and intervals 100 milliseconds.

As you can see, these results appear as if the data is not synchronous. I checked the tool but I didn’t see any problem. Do you have any idea on this topic?

**Comment by clynamen** [comment]
@StepTurtle sorry, I am not maintaining this repo since a long time and I am not actively developing OSS currently. 

I would check manually the timestamps from the original data, maybe they are also not synchronous

**Comment by StepTurtle** [comment]
I understand you. I am also examining the original dataset. The timestamps from the original dataset are similar to the timestamps from the rosbag. I'm sharing the following images in case anyone else encounters a similar problem.

![Figure_1](https://github.com/user-attachments/assets/1ba1d868-bd0e-4747-bc24-91beb30d74df)

They mentioned in their paper that the cameras work in sync. Based on this information, I thought that all the cameras would have close timestamps. However, upon examining the data, I see that even though they don't come at the same time, they do follow a certain pattern. I guess this is also a kind of synchronization, but I'm not very knowledgeable on the subject.

Good luck.
